FROM node:12 as builder
ARG module
WORKDIR /home/node/app

COPY . .
RUN make deps
RUN make build-2-step

FROM node:12-alpine
ARG module
EXPOSE 8080
WORKDIR /home/node/app

COPY --from=builder /home/node/app/2-step/$module/dist ./
COPY --from=builder /home/node/app/2-step/$module/package.json ./

CMD ["yarn", "server"]
