
export const configEthers = {
  PROVIDER_TYPE: 'ETH_PROVIDER_TYPE',
  CUST_PROVIDER_URL: 'ETH_PROVIDER_LOCAL_URL',
  PROVIDER_NETWORK_ID: 'ETH_PROVIDER_NETWORK_ID',
  ETHERSCAN_API_KEY: 'ETHERSCAN_API_KEY',
  INFURA_PROJECT_ID: 'INFURA_PROJECT_ID',
  INFURA_PROJECT_SECRET: 'INFURA_PROJECT_SECRET'
};

export enum EEthersNetwork {
  ETH_MAIN = 'homestead',
  ETH_TEST_KOVAN = 'kovan',
  ETH_TEST_RINKEBY = 'rinkeby',
  default = ETH_MAIN
};
