/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg =
  | {
      set_latest_round_data: {
        data: LatestRoundData;
      };
    }
  | {
      set_oracle_status: {
        status: OracleStatus;
      };
    };
//export type Uint128 = string;
export type OracleStatus = 'Testing' | 'Running' | 'Stopped';

/**
 * Latest round data for an Oracle of type Aggregator
 */
export interface LatestRoundData {
  current: number;
  updated_at: number;
}
